### ISSUE TITLE
Check-in Links Swagger should update the example for the channel field to be uppercase

### ISSUE THREAD

**Issue by pietrini** [pietrini/amadeus-android#5]
This one is linked with issue #4 
For file: Flight_Check-In_Links_Swagger_specification.json

```
definitions:
  CheckinLink:
    required:
      - type
      - id
      - href
      - channel
    properties:
      [...]
      channel:
        description: indicates the type of channel supported by the URL
        type: string
        enum:
          - MOBILE
          - WEB
          - ALL
        example: Mobile
```
